apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgdata
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-lvm

  local:
    path: /var/lib/k8s-local-pv/pgdata

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-manager
