apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-data
spec:
  capacity:
    storage: 2Gi

  volumeMode: Filesystem

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain
  storageClassName: redis-local-storage

  local:
    path: /opt/mentoria/redis

  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-manager
