---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.100 docker-manager
        - 172.16.0.101 docker-worker1
        - 172.16.0.102 docker-worker2
        - 172.16.0.103 docker-registry registry
        
    - name: Definir permissão de acesso da HOME do usuário suporte
      file:
        path: /home/suporte
        owner: suporte
        group: suporte
        state: directory
        recurse: yes
        mode: 0755
