---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.100 manager
        - 172.16.0.101 worker01
        - 172.16.0.102 worker02
        - 172.16.0.103 registry
        
    - name: Criando o arquivo docker-compose.yaml
      copy:
        src: files/docker-compose.yaml
        dest: /opt
        mode: 0644

    - name: Criando o arquivo webserver-deploy.yaml
      copy:
        src: files/webserver-deploy.yaml
        dest: /opt
        mode: 0644

    - name: Definir permiss찾o de acesso ao arquivo webserver-deploy.yaml
      file:
        path: /opt/webserver-deploy.yaml
        owner: suporte
        group: suporte

    - name: Criando diret처rio webserver
      synchronize:
        src: files/webserver
        dest: /home/suporte

    - name: Criando diret처rio storage
      synchronize:
        src: files/storage
        dest: /home/suporte

    - name: Definir permiss찾o de acesso da HOME do usuario suporte
      file:
        path: /home/suporte
        owner: suporte
        group: suporte
        state: directory
        recurse: yes
        mode: 0755
