---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.100 manager
        - 172.16.0.101 worker01
        - 172.16.0.102 worker02
        - 172.16.0.103 registry
        
    - name: Ajustando .bashrc do usuário vagrant
      lineinfile:
        path: /home/vagrant/.bashrc
        line: 'sudo su - suporte'
        
    - name: Instalando pacotes de dependencias para o curso de Docker
      yum:
        name: ['unzip', 'wget', 'elinks', 'rsync']

    - name: Adicionar usuário suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Criando o arquivo docker-compose.yaml
      copy:
        src: files/worker01/docker-compose.yaml
        dest: /opt
        mode: 0644

    - name: Criando diretório webserver
      synchronize:
        src: files/webserver
        dest: /home/suporte

    - name: Criando diretório storage
      synchronize:
        src: files/storage
        dest: /home/suporte

    - name: Criando diretório scripts
      synchronize:
        src: files/worker01/scripts
        dest: /home/suporte
       
    - name: Definir permissão de acesso da HOME do usuario suporte
      file:
        path: /home/suporte
        owner: suporte
        group: suporte
        state: directory
        recurse: yes
        mode: 0755

    - name: Alterando arquivo do SELinux
      lineinfile:
          path: /etc/selinux/config
          regexp: '^SELINUX='
          line: 'SELINUX=disabled'

    - name: Desabilitando o Firewall
      command: systemctl disable firewalld

    - name: Parando FirewallD
      command: systemctl stop firewalld
