---
abstract: 'MooX::Options + MooX::Cmd + Sanity'
author:
  - 'Andrew Rodland <arodland@cpan.org>'
build_requires:
  Capture::Tiny: '0'
  Test::Lib: '0'
  Test::More: '1'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CLI-Osprey
no_index:
  directory:
    - t
requires:
  Getopt::Long::Descriptive: '0.100'
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '0'
  Path::Tiny: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=CLI-Osprey
  homepage: http://metacpan.org/release/CLI-Osprey
  license: http://dev.perl.org/licenses/
  repository: git://github.com/arodland/CLI-Osprey.git
version: '0.08'
x_authority: cpan:ARODLAND
x_serialization_backend: 'YAML::Tiny version 1.70'
