services:
  ha-proxy:
    image: haproxy:2.9
    container_name: ha-proxy
    hostname: ha-proxy

    ports:
      - "80:80"

    volumes:
      - type: bind
        source: ./conf/haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
        read_only: true

    networks:
      network-mentoria:
        ipv4_address: 192.168.56.124

    restart: unless-stopped

networks:
  network-mentoria:
    external: true
