---
abstract: 'easy database connections for Dancer2 applications'
author:
  - 'David Precious <davidp@preshweb.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
  HTTP::Request::Common: '0'
  Plack: '1.0032'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.18, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dancer2-Plugin-Database
no_index:
  directory:
    - t
    - inc
requires:
  Dancer2: '0.166001'
  Dancer::Plugin::Database::Core: '0.16'
resources:
  bugtracker: https://github.com/bigpresh/Dancer-Plugin-Database/issues
  homepage: https://github.com/bigpresh/Dancer-Plugin-Database/
  repository: https://github.com/bigpresh/Dancer-Plugin-Database
version: '2.17'
