---
abstract: 'Perl extension to test methods for warnings'
author:
  - 'Janek Schleicher <bigj@kamelfreund.de>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
keywords:
  - testing
  - warnings
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Warn
no_index:
  directory:
    - t
    - inc
provides:
  Test::Warn:
    file: Warn.pm
    version: '0.37'
requires:
  Carp: '1.22'
  Sub::Uplevel: '0.12'
  Test::Builder: '0.13'
  Test::Builder::Tester: '1.02'
  perl: '5.006'
resources:
  repository: git://github.com/hanfried/test-warn.git
version: '0.37'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
