pipeline {
  environment {
    registry = "dtr.dexter.com.br/analista1/wordpress-devops"
    registryCredential = 'docker-registry'
  }
  agent any
  stages {
    stage('Clonar Repositório do GitLab') {
      steps {
        git 'http://gitlab.dexter.com.br/suporte/wordpress.git'
      }
    }
    stage('Construir imagem Docker') {
      steps{
        sh "sudo docker build . -t '$registry:${env.GIT_BRANCH}-temp'"
      }
    }
    stage('Testar imagem Docker'){
      steps{
          sh "sudo docker container run -d --name 'webserver-${env.GIT_BRANCH}' '$registry:${env.GIT_BRANCH}-temp'"
          sh "sudo docker container rm -f 'webserver-${env.GIT_BRANCH}'"
    }
  }
    stage('Enviar imagem ao DTR') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-registry', passwordVariable: 'dockerDTRPassword', usernameVariable: 'dockerDTRUser')]) {
          sh "sudo docker login -u ${env.dockerDTRUser} -p ${env.dockerDTRPassword} dtr.dexter.com.br"
          sh "sudo docker tag '$registry:${env.GIT_BRANCH}-temp' $registry:${env.GIT_BRANCH}"
          sh "sudo docker push $registry:${env.GIT_BRANCH}"
        }
      }
    }
    stage('Remover imagem Docker temporária') {
      steps{
        sh "sudo docker rmi -f '$registry:${env.GIT_BRANCH}-temp'"
      }
    }
  }
}
