version: '3.9'

services:

  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      REDIS_PASSWORD: "4linux"
      REDIS_DISABLE_COMMANDS: "FLUSHDB,FLUSHALL"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    ports:
      - "6379:6379"
    networks:
      - "live-labs-swarm"
    volumes:
      - "redis-data:/bitnami/redis/data"

  perl-dancer:
    image: "<sua-conta-docker-hub>/dancer-perl:latest"
    environment:
      REDIS_SERVER: "10.128.0.2"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "4linux"
    deploy:
      mode: replicated
      replicas: 1 
      placement:
        constraints: [node.labels.app == perl-dancer]
      restart_policy:
        condition: on-failure
        delay: 10s
      resources:
        limits:
          memory: 256M
          cpus: '0.3'
    ports:
      - ":8080"
    networks:
      - "live-lab-swarm"
    volumes:
      - "perl-data:/opt"

networks:
  live-labs-swarm:
    external: true

volumes:
  redis-data:
    external: true
  perl-data:
    external: true
