apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-server
spec:
  serviceName: redis-server
  replicas: 1

  selector:
    matchLabels:
      app: redis-server

  template:
    metadata:
      labels:
        app: redis-server

    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule

      containers:
        - name: redis-server
          image: redis:7
          imagePullPolicy: IfNotPresent

          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

          volumeMounts:
            - name: redis-data
              mountPath: /data

          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: pvc-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
spec:
  type: ClusterIP

  selector:
    app: redis-server

  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
