---
abstract: 'AppConfig is a bundle of Perl5 modules for reading configuration files and parsing command line arguments.'
author:
  - 'Andy Wardley <abw@wardley.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Pod: '1.0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AppConfig
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  perl: '5.008008'
resources:
  repository: git://github.com/neilbowers/AppConfig.git
version: '1.71'
