---
abstract: 'comprehensive template processing system'
author:
  - 'Andy Wardley <abw@wardley.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Template-Toolkit
no_index:
  directory:
    - t
    - inc
resources:
  bugtracker: https://github.com/abw/Template2/issues
  homepage: http://www.template-toolkit.org
  repository: https://github.com/abw/Template2.git
version: '3.101'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
