---
abstract: 'Minimalist Object Orientation (with Moose compatibility)'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::Fatal: '0.003'
  Test::More: '0.94'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.58, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Moo
no_index:
  directory:
    - t
    - xt
recommends:
  Class::XSAccessor: '1.18'
  Sub::Util: '0'
requires:
  Carp: '0'
  Class::Method::Modifiers: '1.10'
  Exporter: '0'
  Role::Tiny: '2.002003'
  Scalar::Util: '1.00'
  Sub::Defer: '2.006006'
  Sub::Quote: '2.006006'
  perl: '5.006'
resources:
  IRC: irc://irc.perl.org/#moose
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Moo
  license: https://dev.perl.org/licenses/
  repository: https://github.com/moose/Moo.git
version: '2.005004'
x_authority: cpan:MSTROUT
x_breaks:
  App::Commando: '<= 0.012'
  File::DataClass: '<= 0.54.1'
  HTML::Restrict: '== 2.1.5'
  MooX::Emulate::Class::Accessor::Fast: '<= 0.02'
  MySQL::Workbench::Parser: '<= 0.05'
  WebService::Shutterstock: '<= 0.006'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
