---
abstract: "Plack::Middleware which sets body for redirect response, if it's not already set"
author:
  - 'Upasana <me@upasana.me>'
build_requires:
  HTTP::Request::Common: '0'
  Plack::Builder: '0'
  Plack::Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Plack-Middleware-FixMissingBodyInRedirect
requires:
  HTML::Entities: '0'
  Plack::Middleware: '0'
  Plack::Util: '0'
  Scalar::Util: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/Sweet-kid/Plack-Middleware-FixMissingBodyInRedirect/issues
  homepage: https://github.com/Sweet-kid/Plack-Middleware-FixMissingBodyInRedirect
  repository: https://github.com/Sweet-kid/Plack-Middleware-FixMissingBodyInRedirect.git
version: '0.12'
